services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml
      - prom_db_storage:/prometheus


  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_storage:/alertmanager

#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'

  scheme-registry:
    image: confluentinc/cp-schema-registry:8.1.0
    ports:
      - "8085:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://host.docker.internal:9092


volumes:
  prom_db_storage:
  alertmanager_storage:
